travis:
  secure:
    BINSTAR_TOKEN: aS/6Ml8iFWANnGWiGpH7qq4H61mRudrqnEVeV1ocMfizcEsBkAERUiFpK1cMjWWjdz8YFnbd4mEOiXKdqU0lLWkgDsFfSYNbvnfx3t4mA7k8niDxxyRe3xW8kIjZ9ihPtnJ7LP2uNVFSSfndj8+3uHl107SYkz6ragJD7oz7TMEwxE8Y88U9iH4MZwZpfzKFN2V+XoHSwF2h4ZGsv+Wv4Rr3PJ/v+CziHBEzcworgyHxGZSALVjhYNiIzklygROUvctGL22aPhm3+TRM2eqxTr4IPUKPUJ86R2bWt+VK1wuc6XdT4MfudmUWcndPIjUAQh/uTVktysP8ljTU/QqpHM1SktdsBH9oHmEC/sgJYTVFoE6i2Qp7dOmTPXsqMWkhgCBSkY0grNCG9h5oCwH6CVsorrT/f/rQiz5RLPrZCCBxn72RZAMhwS3Wjl+p+OgnpXgDQXMgdA1QT3ew/U3brvUvGDmu53TxgqVIKlnk/+3JSxWENQwWdXq5geqsfbLo6Zd+U/9nxHPiWb89ocReDbWE/W+9EcRgySgaC1AeUnyfmBX1CWjHN8X8trYD+opYHepxeKETuNfQQgH5o4Y6Jt6IZQLDI/AXy9290Xc5jkVoSkYHw/zq0jOWpfgGMzFkrGeJCUqolBQxqhLjggFPddxEbPf/7ukDPvtrsOzhZ6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
