travis:
  secure:
    BINSTAR_TOKEN: ST+IcyvZdYWHZl1/RuBCSKJ4AQNzTGZJf+F6ruojEVNosIuxZOR1YiDlYAOqrgOAN63R4K3ryE0ccQyhiuUcEnDROwzOzgZWnzvjR4pEj4TEVkPFnROkipcbcHCRp+Ie9Vm4XThTWEJBspsAhCRBVMIOYWr3s3Z5I9ahO0RGsydppKdRzHCUWr6zMwptRgnVXVXRGLaVSRcdDq0DjaRTpl1RLMfh8XrBtwvG0mCjuEZtfW89qACI4HbNuY9rznN5fwJpiFTHe/jkAU0qTzQ8rDNE7/F9o28Df4kPQuknkQ0RMVSfVkYM56HPMshqHwoqSI7O9fMR/y0VZj48LmTdYHHQFJQwsz+h+PvOJpyaC0IVmO8bzY56ReBBgaUKxEn/l8+MygiareD+yd17pbvy+QQlrEjDpabOghgj80pUGPMrmDqhrktlxJ7K3HmuaIkBDCGduR5+3N+ZbtGzfq4tjiAXgyvAh4sOke+2K+DiClXuyIDxVtovIw3Uvc88HDZwKKdITFmP4qsoWkS5ztBh/OJRjhCmKBChMOwkEUoC8EouPRx8eLNpMcBYEOp3TwGt1TCjyJAXZI2MWGKOt3IQu9YVXIbYK31UG4CVcZmSJml6uPPWanOM526LPNBDwzCYWdbtz/1ti/JLOGmmxaZZkoOswZGaHvPvTBrXTF8Rhek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
